name: Terraform Docs

on:
  push:
    branches:
      - integration
    paths:
      - '**.tf'
      - '**.terraform-docs.yml'
      - '.github/workflows/**.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Terraform Docs Update
    # Skip this job for merges from main to integration (mostly because of hotfixes), the head_commit message starts with "Merge branch 'main' into integration" for local branch (git merge main) or "Merge remote-tracking branch 'origin/main' into integration" for remote branch (git merge origin/main).
    if: |
      !startsWith(github.event.head_commit.message, 'Merge branch ''main''') &&
      !startsWith(github.event.head_commit.message, 'Merge remote-tracking branch ''origin/main''')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # PAT required to bypass branch protection rules (GITHUB_TOKEN cannot bypass them)
          token: ${{ secrets.TEMPLATES_TOKEN }}

      - name: Generate terraform-docs for AAP Configuration
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-aap-configuration
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for AAP/ASM Configuration
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-aapasm-configuration
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for BMP - New Transactional Endpoint
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-bmp-endpoints
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for Datastream
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-ds2
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for CPS - DV SAN Cert
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-dv-san-cert
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for EDNS
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-edns
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for Property
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-property
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for CPS - Third Party Cert
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-third-party-cert
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true

      - name: Generate terraform-docs for DOM
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: ./new-dom
          config-file: ../.terraform-docs.yaml
          output-file: README.md
          output-method: inject
          git-push: true